### PR TITLE
Python port of the salary data example 

### LINKED ISSUE #104: Port the salary example to Python
Let's see if we can get the json for the key frames of this datamation when it's written in Python/Pandas:

```
"small_salary %>% 
  group_by(Degree) %>%
  summarize(mean = mean(Salary))" %>%
  datamation_sanddance()
```

In Python the analysis could should be something more like this:

```small_salary.groupby("Degree").mean("Salary")```

where `small_salary` is a Pandas dataframe.

Challenges here:

0. What's the right line of Pandas code to mimic the R code above (the `eval()` function)?
1. How do we programmatically parse Python / Pandas code (from a string, for instance)?
2. We need the intermediate data frames at each step
3. And then need to generate datamation-compatible json blobs of vegalite specs

CSV of the data is [here](https://github.com/microsoft/datamations/blob/main/data-raw/small_salary.csv)

cc @chisingh until your account is added to the repo.

### PR DESCRIPTION
**Pull request by chisingh**
This is a basic working example with the salary data to generate plots inside Jupyter notebooks. Closes #104

### CODE REVIEW

**Comment by jhofman** [comment]
@sharlagelfand will have a look over, @jhofman will try to clone and render the notebook for reproducibility

**Comment by sharlagelfand** [comment]
Thanks @chisingh! Just some initial thoughts here, mainly around consistency and how the python code fits within the existing repo (which follows the structure of an R package, for now):

* Could we rename the `datamations` folder to e.g. `python`, and everything would be self-contained in there? Then, if we decide to put all the R code into a folder, it could just go in e.g. `R` and follow the same convention, plus it's clearer from looking at the main repo what it contains.
* Because the current structure is that of an R package, I can ignore entire folders in the R package building process (e.g. `sandbox` is ignored) but it gets a bit complicated if things are mixed, e.g. the python tests living within the same folder as the R tests. Could the [python tests](https://github.com/chisingh/datamations/tree/main/tests/tests) live within the [python folder](https://github.com/chisingh/datamations/tree/main/datamations)?
* Related, can the [test python specs](https://github.com/microsoft/datamations/blob/main/sandbox/groupby_work.json) live in the python folder, e.g. in `python/tests/test_specs` or something like that, so it's clear that these are specs used for formal testing rather than `sandbox`, which is more for playing around while working out new features.
* It would be nice if the [python README](https://github.com/chisingh/datamations/tree/main/datamations#datamation) contained a rendered example, e.g. the same way the [main README](https://github.com/microsoft/datamations#plot-based-datamations) does - these are just screen captures of the resulting animation, but it's nice to see that things "work the same" without running the notebook myself!
* The main function name is not consistent between R and Python - `datamation_sanddance()` versus `datamation()` in Python - I assume we want to stick with the same one

I think that's it for now! Excited by your demos of this and to start testing parity 🎉

**Comment by sharlagelfand** [comment]
Thanks - looks good to me, then! Understood re: the folder name becoming the package, all good there then :) I'll push a commit to the main branch that'll ignore the _datamations_ folder so it won't cause issues on the R package checks.

**Review by sharlagelfand — APPROVED** [review]

**Comment by chisingh** [comment]
Thank you!

**Pull request merged**
